name: "Build iOS app"

# on: [push]
on: [workflow_dispatch]

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: build archive and ipaify
        run: |
          wget -O archive.zip "https://www.dropbox.com/scl/fi/fsv1lmd2l75jf18z45pso/6c4a062a-c8fe-11f0-838b-4c496c81ffba.zip?rlkey=puzd4wra59tlwd05np3r5pcoh&dl=1"
          unzip archive.zip -d .

          xcodebuild archive -project project.xcodeproj -scheme 'project' -archivePath project.xcarchive -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

          mkdir Payload
          mv project.xcarchive/Products/Applications/project.app Payload/project.app

          zip -r "project.ipa" "Payload"

          mv project.ipa ${{ runner.temp }}/project.ipa


      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: project
          path: ${{ runner.temp }}/project.ipa
          # you can also archive the entire directory
          # path: ${{ runner.temp }}/build
          retention-days: 3
