name: "Build iOS app"

# on: [push]
on: [workflow_dispatch]

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: build archive and ipaify
        run: |
          wget -O archive.zip "https://www.dropbox.com/scl/fi/9yke0ftm4illo8qaqv7ng/69aa9408-c8fd-11f0-8468-4c496c81ffba.zip?rlkey=sv3sipfbaq3qxy6icsx4k3n7x&dl=1"
          unzip archive.zip -d .

          xcodebuild archive -project "Uncanny Cat Golf.xcodeproj" -scheme 'Uncanny Cat Golf' -archivePath "Uncanny Cat Golf.xcarchive" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

          mkdir Payload
          mv "Uncanny Cat Golf.xcarchive/Products/Applications/Uncanny Cat Golf.app" Payload/uncannycatgolf.app

          zip -r "Uncanny Cat Golf.ipa" "Payload"

          mv "Uncanny Cat Golf.ipa" ${{ runner.temp }}/uncannycatgolf.ipa


      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: uncannycatgolf
          path: ${{ runner.temp }}/uncannycatgolf.ipa
          # you can also archive the entire directory
          # path: ${{ runner.temp }}/build
          retention-days: 3
